#![allow(dead_code, unused_imports, unused_variables, unused_must_use)]
use crate::internal;
use bitcoin::secp256k1::PublicKey;
use lightning::ln::types::ChannelId;
use bitcoin::hash_types::{Txid};
use bitcoin::script::ScriptBuf;
use internal::messages::{AcceptChannel, ChannelReady, FundingCreated, FundingSigned, OpenChannel,
   OnionMessage, NodeAnnouncement, ChannelAnnouncement};
use internal::messages::Message;

/// An event generated by ChannelManager which indicates a message should be sent to a peer (or
/// broadcast to most peers).
/// These events are handled by PeerManager::process_events if you are using a PeerManager.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum MessageSendEvent {
  /// Used to indicate that we've initiated a channel open and should send the open_channel
  /// message provided to the given peer.
  SendOpenChannel {
    /// The node_id of the node which should receive this message
    node_id: PublicKey,
    /// The message which should be sent.
    msg: OpenChannel,
  },
  /// Used to indicate that a funding_created message should be sent to the peer with the given node_id.
  SendFundingCreated {
    /// The node_id of the node which should receive this message
    node_id: PublicKey,
    /// The message which should be sent.
    msg: FundingCreated,
  },
}


#[derive(Clone, Debug)]
#[cfg_attr(test, derive(PartialEq))]
pub enum MessageType {
  OpenChannel(OpenChannel),
  NodeAnnouncement(NodeAnnouncement),
  OnionMessage(OnionMessage)
}

pub enum Event {
  FundingGenerationReady {
    /// The random channel_id we picked which you'll need to pass into
    /// [`ChannelManager::funding_transaction_generated`].
    ///
    /// [`ChannelManager::funding_transaction_generated`]: crate::ln::channelmanager::ChannelManager::funding_transaction_generated
    temporary_channel_id: ChannelId,
    /// The counterparty's node_id, which you'll need to pass back into
    /// [`ChannelManager::funding_transaction_generated`].
    ///
    /// [`ChannelManager::funding_transaction_generated`]: crate::ln::channelmanager::ChannelManager::funding_transaction_generated
    counterparty_node_id: PublicKey,
    /// The value, in satoshis, that the output should have.
    channel_value_satoshis: u64,
    /// The script which should be used in the transaction output.
    output_script: ScriptBuf,
  },
}

